### ISSUE TITLE
Further wishlist

### ISSUE THREAD

**Issue by ars3niy** [Moult/pyttyplay#1]
* Now in the same ttyrec (2024-11-03.10_43_26.ttyrec) earlier (turn 1429) I eat and permainventory  gets a glitch.
![image](https://github.com/user-attachments/assets/c22f9b0f-0b14-4f23-9380-a3d096f71b94)
* Cursor stays at the bottom right, it needs to be where ttyrec puts it because that is how player character is highlighted.
* Rewind does not quite work, for example: fast forward to the very end of the same ttyrec, than start rewinding. It will not go further back than turn 1520, and then with partially-drawn screen.
* hjkl keyboard shortcuts should be avoided because they are counterintuitive to those with different keyboard layouts such as dvorak.
* The player should only use one line to display its own information at the bottom, rather than three, and there should be an option to turn even that off.

**Comment by Moult** [comment]
09:20 <Arseniy> Also forward/rewind by one frame is not enough, there needs to be a way to seek in steps of different sizes including much bigger ones. Sometimes you'd be looking for a specific turn in a thousands-of-turns long recording, being able to jump hundreds of turns (or several minutes) back and forth is important.

09:34 <Moult> Arseniy: what if +- was used for speed control, then pgup/pgdn, up/down, left/right just like mplayer

09:13 <Arseniy> No, but I got one more scrolling bug: here https://hdf-eu.s3.amazonaws.com/ttyrec/D/DoktorL/nethack/ttyrec/2024-12-14.19:56:11.ttyrec.gz on turn 627 I pick up a lichen corpse and game area corrupts

09:47 <Arseniy> Another problem: this recording https://hdf-us.s3.amazonaws.com/ttyrec/D/DoktorL/tnnt/ttyrec/2024-11-03.09:21:29.ttyrec.gz wait for it to fully load, then hold shift+L do seek all the way to the end, the picture stops updating just after frame 4000

**Comment by Moult** [comment]
All resolved, closing unless more issues come up.
